### ISSUE TITLE
Export as PDF

### ISSUE THREAD

**Issue by shaD1248** [shaD1248/ajman_app_2#3]
**Description**: Introduce the capability to export joist designs as PDF files. This feature will allow users to generate a printable or shareable document of their joist designs.

**Tasks**:

- [ ] Explore and integrate a suitable library for converting HTML or other representations to PDF.
- [ ] Create a function to initiate the PDF export.
- [ ] Add a user interface option to trigger the export process.
